### PR TITLE
Fallback to query params when access to  web storage API is restricted

### LINKED ISSUE #262: Handle Web Storage API Restrictions
### Expected behavior
When I open a generated html report in a browser tab with restrictions to the Web Storage API I should still be able to operate the expandable (dropdown) execution blocks, filtering and sorting options.

### Actual behavior
In some cases, modern browsers may restrict access to Web Storage APIs which causes an uncaught DOMException in `main.js` when trying to access `sessionStorage` leading to display issues with the generated reports. Particularly the expandable execution blocks which may hide important test result data - but also searching and sorting functionality does not function.

```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
    at initializeFilters main.js:151:9
```

### Steps to reproduce
1. Open a generated report in a browser tab with CSP or iframe sandbox enabled
2. Check console for exception/try to expand (click +) on a dropdown execution block

This behaviour may also occur in some browsers where private/incognito browsing does not give access to web storage APIs.

### Gauge version
```
Gauge version: 1.0.8

Plugins
-------
html-report (4.0.10)
js (2.3.10)
screenshot (0.0.1)
```

While `sessionStorage` is used to persist searches and filtering across different pages to give the feel of an SPA, it shouldn't block JS execution if web storage APIs aren't available.

### PR DESCRIPTION
**Pull request by negiDharmendra**
Fixes #262

Signed-off-by: Dharmendra Singh <dharmenn@thoughtworks.com>

### CODE REVIEW

File: themes/default/assets/js/main.js [hunk 1]
```diff
@@ -305,6 +317,50 @@ var initializers = {
...
+    return true;
+}
+
+class DataStore {
+    constructor(data) {
+        this.data = data;
+    }
+
+    insertItem(key, value) {
+        console.log(`Inserting ${key} : ${value} into data store.`);
```
Comment (sriv) [inline themes/default/assets/js/main.js:335]: remove all `console.log`s please. they are useful only for debugging, and in this case of not much use.

we don't want the browser's console to be clutterred.
